id: P009552
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W8LS19359
  title: རིན་པོ་ཆེ་དྲི་མ་མེད་པའི་སྣང་བ།
  author: ''
  volumes:
    aa1e6921cdb04d4a838d2a2d64e60fbc:
      image_group_id: I8LS19361
      title: ''
      volume_number: 1
      total_pages: 164
      base_file: v001.txt
