id: I63B0417C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T00:36:43+00:00'
last_modified: '2022-06-08T11:50:23.301848+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS19359
  title: རིན་པོ་ཆེ་དྲི་མ་མེད་པའི་སྣང་བ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '1650':
      image_group_id: I8LS19361
      title: ''
      total_pages: 164
      order: 1
      base_file: 1650.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
